# Generated by Django 6.0.3 on 2026-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')])),
                ('phone', models.CharField(max_length=15)),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('Ab', 'Ab'), ('O+', 'O+'), ('O-', 'O-'), ('Ab-', 'Ab+')])),
                ('Address', models.TextField()),
            ],
        ),
    ]
