# Generated by Django 6.0.3 on 2026-04-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Address',
            new_name='address',
        ),
    ]
