# Generated by Django 6.0.3 on 2026-04-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
