# Generated by Django 6.0.3 on 2026-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.CharField()),
                ('phone', models.CharField(max_length=12)),
                ('specilization', models.CharField()),
            ],
        ),
    ]
